### ISSUE TITLE
Linked stylesheet is not inlined before sending to Litmus

### ISSUE THREAD

**Issue by notasausage** [jeremypeter/gulp-litmus#7]
I recently switched my gulp tasks from using [gulp-email-builder ](https://github.com/Email-builder/gulp-email-builder) to gulp-litmus, mostly because the former will hang on sending an updated test to Litmus. The problem I have with gulp-litmus is that it does not inline my CSS from a linked stylesheet in the head of my HTML, which gulp-email-builder does by default. Instead I have to also use [gulp-inline-css](https://github.com/jonkemp/gulp-inline-css) before sending a test to Litmus.

Would it be possible to include this functionality in gulp-litmus to reduce steps? Or at least mention the need for inlining before sending a test to Litmus?

**Comment by jeremypeter** [comment]
@notasausage The new version of gulp-email-builder `v2.0.0` shouldn't hang on Litmus tests now. 

I wrote this plugin to only send test to Litmus. I wanted to leave it to the developer on how they'll want to process their HTML before handing it to `gulp-litmus`.
